title: VG web things
description: VG web things on GitHub Pages.

paginate: 50
permalink: pretty
timezone: Europe/Athens
sass:
  style: compressed

collections:
  snippets:
    output: true

jekyll-archives:
  enabled:
    - categories
    - tags

prose:
  media: 'media'
  ignore:
    - /_includes
    - /_layouts
    - _config.yml

gems:
  #- jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
