title: VG web things
description: VG web things on GitHub.
timezone: Europe/Athens
permalink: /:title/

collections:
  snippets:
    output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        layout: "default"
  - scope:
        path: ""
        type: "pages"
    values:
        layout: "default"
  - scope:
        path: ""
        type: "snippets"
    values:
        layout: "snippet"
        tags: []

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

prose:
  media: 'media'
  ignore:
    - /_includes
    - /_layouts
    - _config.yml

gems:
  - jekyll-seo-tag

exclude:
  - _placeholders
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
