title: VG web things
description: VG web things on GitHub.

permalink: pretty
timezone: Europe/Athens
sass:
  style: compressed

collections:
  snippets:
    output: true

defaults:
  - scope:
        path: ""
        type: "pages"
    values:
        layout: "default"
  - scope:
        path: ""
        type: "pages"
    values:
        layout: "default"
  - scope:
        path: ""
        type: "snippets"
    values:
        layout: "snippet"
        categories: []

prose:
  media: 'media'
  ignore:
    - /_includes
    - /_layouts
    - _config.yml

gems:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
